### ISSUE TITLE
No ability to hide temple

### ISSUE THREAD

**Issue by nojvek** [bhujmandir/ddserver#12]
Should have an option of hiding a temple and setting the hidden field.

The api for non logged in user should only show temples that are not hidden.

![image](https://user-images.githubusercontent.com/1018196/29752216-caa1ed00-8b0e-11e7-9bbf-470505502006.png)

**Comment by yogeshkhatri1989** [comment]
Need to clarify issue
1. If there should be option of hidden field, so what is the difference between hidden and remove button as we are setting hidden true for remove
2. Or there should be two fields (hidden and deleted)
3. And for non-logged in users, it uses the old api which returs temples list by looking at directories. As old api is untouched, so it doesn't check for hidden field for non-logged in users. So should it be changed to 
 - Traverse directory and check for hidden field in realm
 - Get list of temples from realm only

**Comment by nojvek** [comment]
Yes hidden basically hides it from non logged in users.

Admin should still be able to see it. But see status as hidden.

You are right. We should have true delete for temples as well. Incase you
make an error. Sorry I totally missed that. True delete just removes dB
entry. No change in folder data

**Comment by yogeshkhatri1989** [comment]
Have added hidden functionality
Admin can hide/unhide temple from dashboard
remove will remove temple from db now.
Non logged in users only only shown hidden=false temples

**Comment by nojvek** [comment]
Perfect thanks. I will take a look tonight.

**Comment by nojvek** [comment]
Deployed latest.

Filed a tiny issue regarding temple names but this is looking great. Good
job.

I will clear your payment tomorrow.

**Comment by yogeshkhatri1989** [comment]
Thanks, will look into the open issues tonight
