### ISSUE TITLE
Temples should use name from realm db

### ISSUE THREAD

**Issue by nojvek** [bhujmandir/ddserver#16]
![image](https://user-images.githubusercontent.com/1018196/30147019-99b27666-9350-11e7-88df-176dd8b38508.png)

**Comment by yogeshkhatri1989** [comment]
to show id, id is now converted to proper name by replacing _ to space as it was done to convert name to id while creating temple.

**Comment by nojvek** [comment]
You had a name field in realm db right?

That's what I used for the script that populates reaalmdb in models/

**Comment by yogeshkhatri1989** [comment]
ok my bad, i forgot about the name field and used id to format it and show it as name. I will fix it today

**Comment by yogeshkhatri1989** [comment]
Fixed
