### ISSUE TITLE
Font awesome icons for buttons

### ISSUE THREAD

**Issue by nojvek** [bhujmandir/ddserver#4]
![image](https://user-images.githubusercontent.com/1018196/28378528-571de4d2-6c65-11e7-9a9c-514ea403858a.png)

http://fontawesome.io/icons/

Add new temple = fa-plus
Log  = fa-file-text-o
Temple = fa-list
User = fa-user-o

Font awesome has icons for google and facebook that you can use in login.

**Comment by yogeshkhatri1989** [comment]
Fixed
